# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3271a82643502a1a632941ab81020de311be56d5f97ee070d4971372f6d66e559ae18a62a66d2fbd89e3a72fd961473fd2e93473cc2f30af7a2834e16f41612d

test:
  secret_key_base: bc0ab112ec56ae59b04645114c78b6f104994b45a316073beda0cf02af27f238c6379c6f03611c84d12e26a9e64c9caf07898511934249e945028b90f7cd9879

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
